os: linux
language: node_js
node_js:
- '16.18.0'
dist: trusty
branches:
  only:
  - source
before_install:
- export TZ=Asia/Taipei
- yarn global add hexo-cli
- yarn global add hexo-deployer-git
install:
- yarn install
script:
- hexo clean
- hexo generate
after_success:
- git config --global user.name 'Jeff Wu'
- git config --global user.email 'a60985182@hotmail.com'
- sed -i'' "/^ *repo/s~github\.com~${GITHUB_TOKEN}@github.com~" _config.yml
- hexo deploy
cache:
  directories:
  - node_modules
