# Header
menu:
  Home: /
  Archives: /archives
  Github: https://jeffwu85182.github.io
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- recent_comment
# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-79727724-2
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
